[package]
name = "safe_core_neon"
version = "0.1.0"
authors = ["MaidSafe devs"]
license = "GPL-3.0"

[lib]
name = "safe_core_neon"
crate-type = ["dylib"]

[dependencies]
maidsafe_utilities = "~0.8.0"
neon = "~0.1"
safe_core = "~0.18.1"
